import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  pl: {
    translation: {
      greeting:
        "Hej! Tu Olek, student Inżynierii Zarządzania i członek KN Falcon.",
      city: "Miasto",
      university: "Uczelnia",
      fieldOfStudy: "Kierunek",
      project: "Projekt",
      universityValue: "Politechnika Wrocławska",
      fieldOfStudyValue: "Inżynieria Zarządzania",
      projectValue: "KN Falcon · SFERA",
      skills: "Kompetencje",
      skillsNote:
        "Pasek postępu bazuje na 10-pytaniowym teście z ChatGPT, należy go traktować raczej jako ciekawostkę niż wiarygodny wskaźnik.",
      skillExcel: "Microsoft Excel",
      skillPowerPoint: "Microsoft PowerPoint",
      skillWord: "Microsoft Word",
      skillJira: "Jira i prowadzenie sprintu",
      skillTeamwork: "Praca zespołowa",
      skillAgile: "Agile i Scrum",
      secondSkillLabel: "Bardzo dobrze",
      projects: "Doświadczenie i rozwój",
      sferaTitle: "Projekt SFERA",
      sferaMeta: "KN Falcon · projekt studencki",
      sferaDescribe:
        "Jako członek Koła Naukowego Falcon rozwijam projekt SFERA. Zdobywam praktyczne doświadczenie w pracy zespołowej i realizacji projektu.",
      googleTitle: "Google Agile Project Management",
      googleMeta: "Ukończony kurs",
      googleDescribe:
        "Ukończyłem kurs Agile Project Management od Google, rozwijając wiedzę o prowadzeniu projektów w metodykach zwinnych.",
      contact: "Kontakt",
      describeYs:
        "Rozwijam się w obszarze zarządzania projektami. Łączę studia z pracą w kole naukowym, a w projektach najlepiej czuję się przy organizacji pracy zespołu, planowaniu sprintów i dbaniu o sprawną komunikację.",
      lightMode: "Tryb jasny",
      darkMode: "Tryb ciemny",
      personalInfo: "O mnie",
      homePage: "Strona główna",
      scrollToSkills: "Przewiń do kompetencji",
      themeSwitch: "Przełącz tryb jasny/ciemny",
      menuToggle: "Otwórz lub zamknij menu",
      cvLocation: "Wrocław",
      cvStudent: "student Inżynierii Zarządzania",
      cvUniversity: "Politechnika Wrocławska",
      cvDegree: "Inżynieria Zarządzania",
      cvGraduation: "Przewidywane ukończenie: styczeń 2028",
      cvFalcon: "Koło Naukowe Falcon",
      cvFalconDescription: "Członek koła naukowego · projekt SFERA",
      cvPresent: "Obecnie",
      cvGoogleDescription:
        "Ukończony kurs z zakresu zwinnego zarządzania projektami",
      cvCompleted: "Ukończony",
      footer: "Stworzone z pasją, nie przez robota",
    },
  },
  en: {
    translation: {
      greeting:
        "Hi! I'm Olek, a Management Engineering student and a member of KN Falcon.",
      city: "City",
      university: "University",
      fieldOfStudy: "Field of study",
      project: "Project",
      universityValue: "Wrocław University of Science and Technology",
      fieldOfStudyValue: "Management Engineering",
      projectValue: "KN Falcon · SFERA",
      skills: "Skills",
      skillsNote:
        "The progress bar reflects a 10-question test generated by ChatGPT and should be viewed more as a fun gimmick than a definitive metric.",
      skillExcel: "Microsoft Excel",
      skillPowerPoint: "Microsoft PowerPoint",
      skillWord: "Microsoft Word",
      skillJira: "Jira and sprint facilitation",
      skillTeamwork: "Teamwork",
      skillAgile: "Agile and Scrum",
      secondSkillLabel: "Very good",
      projects: "Experience and development",
      sferaTitle: "SFERA project",
      sferaMeta: "KN Falcon · student project",
      sferaDescribe:
        "As a member of the Falcon Scientific Circle, I contribute to the SFERA project. I gain practical experience in teamwork and project delivery.",
      googleTitle: "Google Agile Project Management",
      googleMeta: "Completed course",
      googleDescribe:
        "I completed Google's Agile Project Management course, expanding my knowledge of running projects with agile methodologies.",
      contact: "Contact",
      describeYs:
        "I am developing my skills in project management. I combine my studies with work in a scientific circle, and I feel most confident organising team work, planning sprints and ensuring clear communication.",
      lightMode: "Light mode",
      darkMode: "Dark mode",
      personalInfo: "About me",
      homePage: "Home",
      scrollToSkills: "Scroll to skills",
      themeSwitch: "Switch light/dark mode",
      menuToggle: "Open or close menu",
      cvLocation: "Wrocław",
      cvStudent: "Management Engineering student",
      cvUniversity: "Wrocław University of Science and Technology",
      cvDegree: "Management Engineering",
      cvGraduation: "Expected graduation: January 2028",
      cvFalcon: "Falcon Scientific Circle",
      cvFalconDescription: "Scientific circle member · SFERA project",
      cvPresent: "Present",
      cvGoogleDescription: "Completed course in agile project management",
      cvCompleted: "Completed",
      footer: "Created with passion, not by a robot",
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "pl",
  fallbackLng: "pl",
  interpolation: { escapeValue: false },
});

export default i18n;
